version: "3.7"

services:

  tortoisebot-ros2-gazebo:
    image: tortoisebot-ros2-gazebo
    container_name: tortoisebot-ros2-gazebo_1
    build: 
      context: .
      dockerfile: ./dockerfiles/dockerfile_tortoisebot_ros2_gazebo
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - rosnet
    restart: "always" 


  tortoisebot-ros2-slam:
    image: tortoisebot-ros2-slam
    container_name: tortoisebot-ros2-slam_1
    build: 
      context: .
      dockerfile: ./dockerfiles/dockerfile_tortoisebot_ros2_slam
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - rosnet
    restart: "always"


networks:
  rosnet:
    driver: bridge