# Start from ROS base image
FROM ros:galactic-ros-base

# Make a catkin workspace
WORKDIR /
RUN mkdir -p /ros2_ws/src
WORKDIR /ros2_ws/src

SHELL [ "/bin/bash" , "-c" ]
# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    git \
    build-essential


RUN apt-get update && apt-get install -y \
  gazebo11 \
  ros-galactic-gazebo-ros-pkgs \
  ros-galactic-joint-state-publisher \
  ros-galactic-robot-state-publisher \
  ros-galactic-cartographer \
  ros-galactic-cartographer-ros \
  --no-install-recommends \
  ros-galactic-gazebo-plugins \
  ros-galactic-teleop-twist-keyboard  \
  ros-galactic-teleop-twist-joy \
  ros-galactic-xacro \ 
  ros-galactic-nav2* \
  ros-galactic-urdf \
  ros-galactic-v4l2-camera \
  ros-galactic-robot-localization \
  ros-galactic-tf2-ros \
  ros-galactic-tf2-tools \
  ros-galactic-rviz2  \
  ros-galactic-gazebo-msgs \
  ros-galactic-joint-trajectory-controller \
  && rm -rf /var/lib/apt/lists/*
 

RUN git clone -b ros2-galactic https://github.com/rigbetellabs/tortoisebot.git /ros2_ws/src/tortoisebot

RUN rm -rf \ 
    /ros2_ws/src/tortoisebot/tortoisebot_firmware \
    /ros2_ws/src/tortoisebot/tortoisebot_control \
    /ros2_ws/src/tortoisebot/tortoisebot_bringup \
    /ros2_ws/src/tortoisebot/tortoisebot_gazebo \
    /ros2_ws/src/tortoisebot/ydlidar-ros2 \
    /ros2_ws/src/tortoisebot/slam 

COPY ./entrypoints /entrypoints
COPY ./tortoisebot/tortoisebot_slam /ros2_ws/src/tortoisebot/tortoisebot_slam

# Build the Catkin workspace
RUN source /opt/ros/galactic/setup.bash \
    && cd /ros2_ws \
    && colcon build

# Ensure the workspace is sourced
RUN echo "source /ros2_ws/install/setup.bash" >> ~/.bashrc

# Set the entry point to start the ROS launch file
ENTRYPOINT ["/bin/bash", "-c", "source /entrypoints/slam_entrypoint.sh"]
#ENTRYPOINT ["/bin/bash", "-c", "source /ros2_ws/install/setup.bash && sleep 10 && ros2 launch tortoisebot_slam cartographer.launch.py use_sim_time:=True"]